# Generated by Django 5.2.5 on 2025-09-22 00:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='progreso',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='facturacion_incompleta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='presupuesto_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('planificado', 'Planificado'), ('presupuestado', 'Presupuestado'), ('aprobado', 'Aprobado'), ('en_progreso', 'En progreso'), ('en_pausa', 'En pausa'), ('finalizado', 'Finalizado'), ('facturacion', 'Facturación'), ('archivado', 'Archivado')], default='planificado', max_length=20),
        ),
        migrations.CreateModel(
            name='FacturaProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('fecha_emision', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='proyectos/facturas/%Y/%m/')),
                ('estado', models.CharField(choices=[('cargada', 'Cargada / A revisión'), ('aprobada', 'Aprobada'), ('pend_acreditacion', 'Pendiente de acreditación'), ('acreditada', 'Acreditada')], default='cargada', max_length=20)),
                ('creada_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('aprobada_en', models.DateTimeField(blank=True, null=True)),
                ('acreditada_en', models.DateTimeField(blank=True, null=True)),
                ('acreditada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_acreditadas', to=settings.AUTH_USER_MODEL)),
                ('aprobada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_creadas', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='proyectos.proyecto')),
            ],
            options={
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='HistorialProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('estado_tarea', 'Cambio de estado de tarea'), ('recordatorio', 'Recordatorio de vencimiento'), ('factura', 'Movimiento de factura'), ('ajuste', 'Ajuste de presupuesto'), ('cierre_incompleto', 'Cierre con facturación incompleta'), ('reapertura', 'Reapertura de proyecto'), ('cierre', 'Cierre de proyecto')], max_length=32)),
                ('descripcion', models.TextField()),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='proyectos.proyecto')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
