# Generated by Django 5.2.5 on 2025-10-13 21:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_remove_proyecto_progreso_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HoraTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('horas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descripcion', models.TextField(blank=True)),
                ('es_facturable', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('cargada', 'Cargada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='cargada', max_length=10)),
                ('aprobada_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('aprobada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horas_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horas_trabajo', to='proyectos.proyecto')),
                ('tarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horas_trabajo', to='proyectos.tarea')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horas_trabajo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hora de trabajo',
                'verbose_name_plural': 'Horas de trabajo',
                'ordering': ('-fecha', '-creado_en'),
                'permissions': [('can_manage_economia', 'Puede acceder al área de economía'), ('can_approve_horas', 'Puede aprobar horas de trabajo')],
            },
        ),
    ]
