# Generated by Django 5.2.5 on 2025-10-20 17:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_horatrabajo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='presupuesto_pdf',
            field=models.FileField(blank=True, null=True, upload_to='proyectos/presupuestos/%Y/%m/'),
        ),
        migrations.AddIndex(
            model_name='adjunto',
            index=models.Index(fields=['subido_en'], name='proyectos_a_subido__94e3ad_idx'),
        ),
        migrations.AddIndex(
            model_name='comentario',
            index=models.Index(fields=['creado_en'], name='proyectos_c_creado__f70d95_idx'),
        ),
        migrations.AddIndex(
            model_name='facturaproyecto',
            index=models.Index(fields=['estado'], name='proyectos_f_estado_2eabc6_idx'),
        ),
        migrations.AddIndex(
            model_name='facturaproyecto',
            index=models.Index(fields=['-creada_en'], name='proyectos_f_creada__7cb2bd_idx'),
        ),
        migrations.AddIndex(
            model_name='facturaproyecto',
            index=models.Index(fields=['numero'], name='proyectos_f_numero_02fde2_idx'),
        ),
        migrations.AddIndex(
            model_name='historialproyecto',
            index=models.Index(fields=['-creado_en'], name='proyectos_h_creado__627864_idx'),
        ),
        migrations.AddIndex(
            model_name='historialproyecto',
            index=models.Index(fields=['tipo'], name='proyectos_h_tipo_6d088f_idx'),
        ),
        migrations.AddIndex(
            model_name='horatrabajo',
            index=models.Index(fields=['estado'], name='proyectos_h_estado_46ab08_idx'),
        ),
        migrations.AddIndex(
            model_name='horatrabajo',
            index=models.Index(fields=['-fecha'], name='proyectos_h_fecha_6ce1bd_idx'),
        ),
        migrations.AddIndex(
            model_name='horatrabajo',
            index=models.Index(fields=['proyecto'], name='proyectos_h_proyect_9b5a1d_idx'),
        ),
        migrations.AddIndex(
            model_name='horatrabajo',
            index=models.Index(fields=['usuario'], name='proyectos_h_usuario_cd4057_idx'),
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['estado'], name='proyectos_p_estado_fd8518_idx'),
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['prioridad'], name='proyectos_p_priorid_29043b_idx'),
        ),
        migrations.AddIndex(
            model_name='proyecto',
            index=models.Index(fields=['-creado_en'], name='proyectos_p_creado__8dbe00_idx'),
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['estado'], name='proyectos_t_estado_d1afc3_idx'),
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['prioridad'], name='proyectos_t_priorid_6715f2_idx'),
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['vence_el'], name='proyectos_t_vence_e_3189ab_idx'),
        ),
    ]
