# Generated by Django 5.2.5 on 2025-11-14 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0006_adjuntoproyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjuntoproyecto',
            name='alias',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
