# Generated by Django 5.2.5 on 2025-11-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0007_adjuntoproyecto_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='horatrabajo',
            name='fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horatrabajo',
            name='inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horatrabajo',
            name='horas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
