# Generated by Django 5.2.5 on 2025-11-10 23:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('phone_number_id', models.CharField(blank=True, max_length=64)),
                ('business_account_id', models.CharField(blank=True, max_length=64)),
                ('token', models.CharField(blank=True, max_length=512)),
                ('verify_token', models.CharField(default='d3s-verify', max_length=128)),
            ],
            options={
                'verbose_name': 'Config WhatsApp Cloud API',
                'verbose_name_plural': 'Config WhatsApp Cloud API',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Nombre (Meta)')),
                ('language', models.CharField(default='es', max_length=10, verbose_name='Idioma')),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plantilla WhatsApp',
                'verbose_name_plural': 'Plantillas WhatsApp',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=32)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('response', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='created', max_length=32)),
                ('provider_message_id', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('error', models.TextField(blank=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notificaciones.whatsapptemplate')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
