# Generated by Django 5.2.5 on 2025-09-06 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaccion',
            options={'ordering': ['-fecha', '-creado_en'], 'permissions': [('view_reports_economia', 'Puede ver el panel de Economía')], 'verbose_name': 'Transacción', 'verbose_name_plural': 'Transacciones'},
        ),
    ]
