# Generated by Django 5.2.5 on 2025-09-06 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economia', '0002_alter_transaccion_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transaccion',
            options={'permissions': [('can_validate_transactions', 'Puede validar transacciones de economía')]},
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='es_reembolso',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='fecha_reintegro',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='reintegrado',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='tipo',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='validado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='validado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('gasto', 'Gasto')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='economia.categoria'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
