# Generated by Django 5.2.5 on 2025-09-06 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economia', '0003_alter_categoria_options_alter_transaccion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaccion',
            options={'permissions': [('can_validate_transactions', 'Puede validar transacciones de economía'), ('can_add_ingresos', 'Puede registrar ingresos en economía')]},
        ),
    ]
