# Generated by Django 5.2.5 on 2025-09-13 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economia', '0006_alter_transaccion_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('monto_esperado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='economia.categoria')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan mensual',
                'verbose_name_plural': 'Planes mensuales',
                'unique_together': {('year', 'month', 'categoria')},
            },
        ),
    ]
