# Generated by Django 5.2.5 on 2025-10-28 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economia', '0007_planmensual'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaccion',
            options={'permissions': [('can_validate_transactions', 'Puede validar transacciones de economía'), ('can_add_ingresos', 'Puede registrar ingresos en economía'), ('can_edit_own_transactions', 'Puede editar sus propias transacciones pendientes'), ('view_dashboard', 'Puede ver el dashboard de Economía')]},
        ),
    ]
