# Generated by Django 5.2.5 on 2025-11-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economia', '0008_alter_transaccion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='comprobante',
            field=models.FileField(blank=True, help_text='PDF o imagen del comprobante', null=True, upload_to='comprobantes/%Y/%m/'),
        ),
    ]
