# Generated by Django 5.2.5 on 2025-11-02 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economia', '0009_transaccion_comprobante'),
        ('proyectos', '0005_tarea_asignados'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='proyectos.proyecto'),
        ),
    ]
