# Generated by Django 5.2.5 on 2025-11-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economia', '0011_tarifahora'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='es_efectivo',
            field=models.BooleanField(default=False, help_text='Marcá si el pago/cobro fue en efectivo.'),
        ),
    ]
