"""
Django settings for d3s_system project.
Generated by 'django-admin startproject' using Django 5.2.5.
"""

from pathlib import Path
import os
import dj_database_url

# ====== Paths ======
BASE_DIR = Path(__file__).resolve().parent.parent

# ====== Seguridad y modo debug ======
SECRET_KEY = os.getenv(
    'SECRET_KEY',
    'django-insecure-f*=!n&k2=+#oind4b$kaggv8b40@8b42*-yd*)2i@q(wn8mwy*'
)
DEBUG = os.getenv('DEBUG', '1') == '1'
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# ====== Apps ======
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "economia",
    "notificaciones",
    "proyectos",
]

# ====== Middleware ======
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # estáticos en prod
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# ====== Templates ======
ROOT_URLCONF = 'd3s_system.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "notificaciones.context_processors.notificaciones_ctx",
            ],
        },
    },
]

WSGI_APPLICATION = 'd3s_system.wsgi.application'

# ====== Base de datos ======
if os.getenv("DATABASE_URL"):
    DATABASES = {
        "default": dj_database_url.parse(os.getenv("DATABASE_URL"), conn_max_age=600)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# ====== Validación de contraseñas ======
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ====== Login/logout ======
LOGIN_REDIRECT_URL = "/perfil/"
LOGOUT_REDIRECT_URL = 'login'

# ====== Internacionalización / Localización ======
LANGUAGE_CODE = "es-ar"
TIME_ZONE = "America/Argentina/Buenos_Aires"
USE_I18N = True
USE_TZ = True
USE_L10N = True  # localización de fechas/números

LANGUAGES = [("es", "Español")]

LOCALE_PATHS = [BASE_DIR / "locale"]

# Formatos locales (Argentina)
USE_THOUSAND_SEPARATOR = True
THOUSAND_SEPARATOR = "."
DECIMAL_SEPARATOR = ","
DATE_FORMAT = "d/m/Y"
DATETIME_FORMAT = "d/m/Y H:i"
SHORT_DATE_FORMAT = "d/m"

# Aceptar dd/mm/aaaa como entrada por defecto
from django.conf.locale.es import formats as es_formats
es_formats.DATE_INPUT_FORMATS = ["%d/%m/%Y"]
es_formats.DATE_FORMAT = "d/m/Y"

# ====== Archivos estáticos y media ======
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ====== Default PK ======
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
